name: publish
'on':
  push:
    branches:
      - ktp-pydata-versions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y pandoc git
        pip3 install -r doc/requirements.txt
        source doc/set_version.sh
        echo Generating version $DOC_VERSION
    - name: build docs
      run: |
        source doc/set_version.sh
        cd doc
        chmod +x build-doc.sh
        ./build-doc.sh
        sphinx-build -b html -D version=$DOC_VERSION sources _build/html
        mv _build/html ../../$DOC_VERSION
        rm -rf _build
        cp versions.json ../..
    - name: deploy docs
      run: |
        source doc/set_version.sh
        git fetch
        git checkout -- doc/build-doc.sh
        git checkout latesthtml
        rm -rf $DOC_VERSION
        mv -f ../$DOC_VERSION .
        mv ../versions.json .
        rm -rf doc
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@github.com"
        git add .
        git commit -m "latest HTML output"
        git push -f https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:latesthtml

