name: publish
'on':
  push:
    branches:
      - ktp-pydata-versions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt install -y build-essential python3
        source doc/set_version.sh
        echo Generating version $DOC_VERSION